# Site settings
author: Matt Etress
title: matt = Developer.new
header-img: img/home-bg.png
email: mattetress@me.com
copyright_name: Matt Etress
description: > # this means to ignore newlines until "baseurl:"
  My Path to Full Stack Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username:
github_username:  mattetress
url: mattetress.github.io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
